### ISSUE TITLE
java.lang.UnsupportedOperationException: StartNodeJS Not Supported.

### ISSUE THREAD

**Issue by bennylut** [eclipsesource/J2V8#157]
Hi, I am attempting to execute the following code: 

```java
public static void main(String... args){
     NodeJS node = NodeJS.createNodeJS();
}
```

and receiving the following exception: 
```
Exception in thread "main" java.lang.UnsupportedOperationException: StartNodeJS Not Supported.
	at com.eclipsesource.v8.V8._startNodeJS(Native Method)
	at com.eclipsesource.v8.V8.createNodeRuntime(V8.java:858)
	at com.eclipsesource.v8.NodeJS.createNodeJS(NodeJS.java:73)
	at com.eclipsesource.v8.NodeJS.createNodeJS(NodeJS.java:43)
	at hello.ngu.j2v8.Test.main(Test.java:21)
```

when executing this code, under the `cwd` there is a directory called `jni` which contains the built `libj2v8_linux_x86_64.so`  library.
this build passed J2V8 tests.

Any idea what is the problem?

**Comment by bennylut** [comment]
I rechecked the tests output: 
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.eclipsesource.v8.LibraryLoaderTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.023 sec - in com.eclipsesource.v8.LibraryLoaderTest
Running com.eclipsesource.v8.NullScriptExecuteTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.455 sec - in com.eclipsesource.v8.NullScriptExecuteTest
Running com.eclipsesource.v8.V8ArrayTest
Tests run: 197, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.169 sec - in com.eclipsesource.v8.V8ArrayTest
Running com.eclipsesource.v8.V8CallbackTest
Tests run: 112, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.372 sec - in com.eclipsesource.v8.V8CallbackTest
Running com.eclipsesource.v8.V8JSFunctionCallTest
Tests run: 58, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.367 sec - in com.eclipsesource.v8.V8JSFunctionCallTest
Running com.eclipsesource.v8.V8LockerTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.eclipsesource.v8.V8LockerTest
Running com.eclipsesource.v8.V8MultiThreadTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 20.035 sec - in com.eclipsesource.v8.V8MultiThreadTest
Running com.eclipsesource.v8.V8ObjectTest
Tests run: 134, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.492 sec - in com.eclipsesource.v8.V8ObjectTest
Running com.eclipsesource.v8.V8RuntimeNotLoadedTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in com.eclipsesource.v8.V8RuntimeNotLoadedTest
Running com.eclipsesource.v8.V8ScriptCompilationExceptionTest
Tests run: 19, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.102 sec - in com.eclipsesource.v8.V8ScriptCompilationExceptionTest
Running com.eclipsesource.v8.V8ScriptExecutionExceptionTest
Tests run: 27, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.555 sec - in com.eclipsesource.v8.V8ScriptExecutionExceptionTest
Running com.eclipsesource.v8.V8Test
Tests run: 141, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.146 sec - in com.eclipsesource.v8.V8Test
Running com.eclipsesource.v8.V8TypedArraysTest
Tests run: 42, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.486 sec - in com.eclipsesource.v8.V8TypedArraysTest
Running com.eclipsesource.v8.debug.BreakEventTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.355 sec - in com.eclipsesource.v8.debug.BreakEventTest
Running com.eclipsesource.v8.debug.DebugHandlerTest
Tests run: 17, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.889 sec - in com.eclipsesource.v8.debug.DebugHandlerTest
Running com.eclipsesource.v8.debug.ExecutionStateTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.596 sec - in com.eclipsesource.v8.debug.ExecutionStateTest
Running com.eclipsesource.v8.debug.FrameTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.176 sec - in com.eclipsesource.v8.debug.FrameTest
Running com.eclipsesource.v8.debug.MirrorTest
Tests run: 19, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.278 sec - in com.eclipsesource.v8.debug.MirrorTest
Running com.eclipsesource.v8.debug.ScopeTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.221 sec - in com.eclipsesource.v8.debug.ScopeTest
Running com.eclipsesource.v8.debug.ScriptBreakPointTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.676 sec - in com.eclipsesource.v8.debug.ScriptBreakPointTest
Running com.eclipsesource.v8.utils.V8ExecutorTest
Tests run: 27, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.935 sec - in com.eclipsesource.v8.utils.V8ExecutorTest
Running com.eclipsesource.v8.utils.V8MapTest
Tests run: 26, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.923 sec - in com.eclipsesource.v8.utils.V8MapTest
Running com.eclipsesource.v8.utils.V8ObjectUtilsTest
Tests run: 103, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.351 sec - in com.eclipsesource.v8.utils.V8ObjectUtilsTest
Running com.eclipsesource.v8.utils.V8PropertyMapTest
Tests run: 26, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in com.eclipsesource.v8.utils.V8PropertyMapTest
```

it does not seem to execute NodeJSTests at all, this is because by default Maven uses the following naming conventions when looking for tests to run:
```bash
Test*
*Test
*TestCase
```

So I renamed NodeJSTests to NodeJSTest and now the tests failing hard..

**Comment by bennylut** [comment]
I've looked at the `com_eclipsesource_v8_V8Impl.cpp` file under the `jni` directory and lines 299-301 read: 

```c++
#ifndef NODE_COMPATIBLE
  (env)->ThrowNew(unsupportedOperationExceptionCls, "StartNodeJS Not Supported.");
#endif
```

but I didn't saw that `com_eclipsesource_v8_V8Impl.h`  define such identifier - so I tried to to define it there (i.e., `#define NODE_COMPATIBLE` somewhere on the start of the file)

rebuild, and test - crush the jvm :(  :
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.eclipsesource.v8.LibraryLoaderTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.023 sec - in com.eclipsesource.v8.LibraryLoaderTest
Running com.eclipsesource.v8.NodeJSTest
Java HotSpot(TM) 64-Bit Server VM warning: You have loaded library /home/bennyl/projects/J2V8/jni/libj2v8_linux_x86_64.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
node.js:840
  var ContextifyScript = process.binding('contextify').ContextifyScript;
                                 ^
Error: No such module: contextify
    at Error (native)
    at node.js:840:34

Results :

Tests run: 12, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by irbull** [comment]
Hi, Sorry about all this trouble.

A few notes:
1. I use `-D NODE_COMPATIBLE=1` when I build J2V8 to enable node. I do this because J2V8 can compile against V8 or Node (historically it was just a wrapper for J2V8). Now, I said "I use -D NODE_COMPATIBLE=1", but that was a lie :-(. Turns out I missed this on my Jenkins server (I use this locally on my Mac).

2. I use a `@SuiteClasses` to list the tests to run (see `AllTests.java`). However, you're right, this does not work with Maven and because I had the wrong name for my test class name, the tests were never running on Linux. :-( (BTW, I fixed this with 06f48667c9a1399574cffb7824fae7e7e2bb36c4).

3. When I use `-D NODE_COMPATIBLE=1` I am now seeing the same error as you. 

After a bit of googling, I found [Node Issue 686](https://github.com/nodejs/node/issues/686). It suggested using a slightly different set of commands to the linker. With the following build line, things appear to work. Can you test this?

```
export CCFLAGS="${CCFLAGS} -fPIC" 
export CXXFLAGS="${CXXFLAGS} -fPIC" 
export CPPFLAGS="${CPPFLAGS} -fPIC" 
#sh ./build-node.sh
cp -r /data/jenkins/node .
cd jni
g++ -I../node -I../node/deps/v8 -I../node/deps/v8/include \
    -I../node/src -I /data/jenkins/tools/hudson.model.JDK/jdk-7/include/ \
    -I /data/jenkins/tools/hudson.model.JDK/jdk-7/include/linux  \
    com_eclipsesource_v8_V8Impl.cpp -std=c++11 -fPIC -shared -o libj2v8_linux_x86_64.so \
    -Wl,--whole-archive ../node/out/Release/libnode.a  -Wl,--no-whole-archive \
    -Wl,--start-group \
                      ../node/out/Release/libv8_libbase.a \
                      ../node/out/Release/libv8_libplatform.a \
                      ../node/out/Release/libv8_base.a \
                      ../node/out/Release/libv8_nosnapshot.a \
                      ../node/out/Release/libuv.a \
                      ../node/out/Release/libopenssl.a \
                      ../node/out/Release/libhttp_parser.a \
                      ../node/out/Release/libgtest.a \
                      ../node/out/Release/libzlib.a \
                      ../node/out/Release/libcares.a \
    -Wl,--end-group \
    -lrt -D NODE_COMPATIBLE=1
```
BTW. I noticed you offered to help try and integrate J2V8 with Angular Universal. Please let me know if I can help in anyway.

**Comment by irbull** [comment]
I should also mention that the .so file is now 20Mb. This makes a bit more sense I think.

**Comment by bennylut** [comment]
Hi, Thank you - it works now, 

> BTW. I noticed you offered to help try and integrate J2V8 with Angular Universal. Please let me know if I can help in anyway.

Sure thank you, currently I have an extremely basic version that only runs the build script and then start the server (need to add live reload, I think that it may require throwing away the NodeJS vm and creating a new one for each reload). Once this is done - I will need to write a simple wrapper to write rest endpoints.

What I would like is to upload the linux release of j2v8 to maven (including the native library in-jar) - this is just to get a git friendly project (i.e., not uploading binary dependencies to git). I don't want to bother you  so, will it be OK if I will clone the library, add the "in-jar" native-library-loading support and maybe the build script for linux including documentation so that you will be able to push it to maven?

**Comment by bennylut** [comment]
Closing this issue as this now works, I will open a new unrelated issue for the warning later today
```
Java HotSpot(TM) 64-Bit Server VM warning: You have loaded library /home/bennyl/projects/J2V8/jni/libj2v8_linux_x86_64.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
```

BTW, 
you can checkout the progress of the Angular Universal + J2V8 project here:
https://github.com/bennylut/hello-angular2-universal-j2v8
