### ISSUE TITLE
Fail to extract bundle file that's "libj2v8_macosx_x86_64.dylib" in jar file.

### ISSUE THREAD

**Issue by uemuran** [eclipsesource/J2V8#165]
I want to use NodeJS module.
So, I build native parts and java parts on MacOS.
And load this jar in my project, and use NodeJS module.
But, i got following error.

`Exception in thread "Thread-6" java.lang.IllegalStateException: J2V8 native library not loaded.
	at com.eclipsesource.v8.V8.checkNativeLibraryLoaded(V8.java:161)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:146)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:122)
	at com.eclipsesource.v8.NodeJS.createNodeJS(NodeJS.java:56)
	at com.eclipsesource.v8.NodeJS.createNodeJS(NodeJS.java:43)
	at com.eclipsesource.v8.angular.UniversalRenderingEngine.initNode(UniversalRenderingEngine.java:132)
	at com.eclipsesource.v8.angular.UniversalRenderingEngine.run(UniversalRenderingEngine.java:57)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons: 
	no j2v8_macosx_x86_64 in java.library.path
	/Users/a13000/libj2v8_macosx_x86_64.dylib: dlopen(/Users/a13000/libj2v8_macosx_x86_64.dylib, 1): no suitable image found.  Did find:
	/Users/a13000/libj2v8_macosx_x86_64.dylib: unknown file type, first eight bytes: 0xEF 0xBF 0xBD 0xEF 0xBF 0xBD 0xEF 0xBF

	at com.eclipsesource.v8.LibraryLoader.loadLibrary(LibraryLoader.java:75)
	at com.eclipsesource.v8.V8.load(V8.java:68)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:142)
	... 6 more
`

Don't you know sothing cause?

**Comment by uemuran** [comment]
libj2v8_macosx_x86_64.dylib is correct. Because, if i use this not bunbled in jar, it works well.
Probably, when extract this file from jar file, this file broken.

**Comment by hsaginor** [comment]
I ran into the same issue and did some debugging. The issues is that file bundles with the jar has a different name than what the code in LibraryLoader is expecting. Inside the jar the file is libj2v8-macosx-x86_64.dylib.

Line 34 in LibraryLoader is adding "_" instead of "-" before and after os name. Other platforms should have the same issue. So, this bug is probably a duplicate.
