### ISSUE TITLE
FAILED BINDER TRANSACTION - Android platform.

### ISSUE THREAD

**Issue by Nims72** [eclipsesource/J2V8#196]
Is there a limit on the size of the JS that can be handled by this framework?

Included is the following error:
E/AndroidRuntime: Error reporting crash
                                                                              android.os.TransactionTooLargeException: data parcel size 1681416 bytes
                                                                                  at android.os.BinderProxy.transactNative(Native Method)
                                                                                  at android.os.BinderProxy.transact(Binder.java:503)
                                                                                  at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4425)
                                                                                  at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
                                                                                  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                                  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

**Comment by vanshg** [comment]
Were you able to get it to run with a large JS library? I'm getting the same error

**Comment by irbull** [comment]
Not that I know of. However, this doesn't seem related to J2V8 as there is nothing J2V8 in that stack trace.

**Comment by vanshg** [comment]
I'm able to load in a small JS file just fine, but when I try to load in a ~1 MB JS file, I get this error. Right before the stack Trace is printed, the entire contents of the js file is logged

**Comment by Nims72** [comment]
@vanshg I did manage to load a large JS file. The error as far as I can remember was due to something wrong in the JS file itself.
