### ISSUE TITLE
Cannot run a basic test using centos 7

### ISSUE THREAD

**Issue by TomerAmirV** [eclipsesource/J2V8#211]
Hi,
I created a test project in `centos 7` and I cannot run it. It does work when I run it on `mac`, but not on centos.

My code:

Main.java
```
package com.test;

import com.eclipsesource.v8.JavaCallback;
import com.eclipsesource.v8.NodeJS;
import com.eclipsesource.v8.V8Array;
import com.eclipsesource.v8.V8Object;

import java.io.File;
import java.io.IOException;

public class Main {

	public static void main(String[] args) throws IOException {
		final NodeJS nodeJS = NodeJS.createNodeJS();
		JavaCallback callback = new JavaCallback() {

			public Object invoke(V8Object receiver, V8Array parameters) {
				return "Hello, JavaWorld!";
			}
		};

		nodeJS.getRuntime().registerJavaMethod(callback, "someJavaMethod");
		File nodeScript = createTemporaryScriptFile("test.js");

		nodeJS.exec(nodeScript);

		while(nodeJS.isRunning()) {
			nodeJS.handleMessage();
		}
		nodeJS.release();
	}

	private static File createTemporaryScriptFile(String path) {
		return new File(path);
	}
}

```

test.js
```
var http = require('http');

var server = http.createServer(function (request, response) {
	response.writeHead(200, {'Content-Type': 'text/plain'});
	response.end(someJavaMethod());
});
server.listen(8000);
console.log('Server running at http://127.0.0.1:8000/');
```

build.gradle
```
group 'com.test'
version '1.0-SNAPSHOT'

apply plugin: 'java'

repositories {
    mavenCentral()
}

sourceCompatibility = 1.7
version = '1.0'
jar {
    manifest {
        attributes  'Implementation-Title': 'Gradle Quickstart',
                    'Implementation-Version': version,
                    'Main-Class': 'com.test.Main'
    }
}

dependencies {
    // https://mvnrepository.com/artifact/com.eclipsesource.j2v8/j2v8_linux_x86_64
    compile group: 'com.eclipsesource.j2v8', name: 'j2v8_linux_x86_64', version: '4.6.0'

    // https://mvnrepository.com/artifact/com.eclipsesource.j2v8/j2v8_macosx_x86_64
    compile group: 'com.eclipsesource.j2v8', name: 'j2v8_macosx_x86_64', version: '4.6.0'


    testCompile group: 'junit', name: 'junit', version: '4.11'
}

```

Exception:
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/eclipsesource/v8/JavaCallback
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.eclipsesource.v8.JavaCallback
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```

**Comment by TomerAmirV** [comment]
My Bad, Forgot to include the dependencies in the build.gradle.

fixed grade:

```
group 'com.vonage'
version '1.0-SNAPSHOT'

apply plugin: 'java'

repositories {
    mavenCentral()
}

sourceCompatibility = 1.8
version = '1.0'

task fatJar(type: Jar) {
    manifest {
        attributes 'Implementation-Title': 'Gradle Jar File Example',
                'Implementation-Version': version,
                'Main-Class': 'com.test.Main'
    }
    baseName = project.name + '-all'
    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
    with jar
}

dependencies {
    // https://mvnrepository.com/artifact/com.eclipsesource.j2v8/j2v8_linux_x86_64
    compile group: 'com.eclipsesource.j2v8', name: 'j2v8_linux_x86_64', version: '4.5.0'

    // https://mvnrepository.com/artifact/com.eclipsesource.j2v8/j2v8_macosx_x86_64
    compile group: 'com.eclipsesource.j2v8', name: 'j2v8_macosx_x86_64', version: '4.6.0'


    testCompile group: 'junit', name: 'junit', version: '4.11'
}

```
