### ISSUE TITLE
V8 object that are passed as arguments to Java methods are released at the end of the method

### ISSUE THREAD

**Issue by TomerAmirV** [eclipsesource/J2V8#224]
This looks like something done on purpose, but I wanted to make sure.

When I register a Java method to V8, and the method has arguments that are V8Objects or V8Functions, they are released once the method returns.

This was bothering me when I tried to save a JS method as a callback that Java would initiate.

Was this intentional? Can it be fixed?
It will be very helpful since this way you could sort of initiate events from Java on JS.

Code example:

Test.java:
```java
import com.eclipsesource.v8.V8Function;

public class Test {
	public V8Function func;

	public void setFunc(V8Function func) {
		this.func = func;
	}
}
```

Main.java:
```java
import com.eclipsesource.v8.V8;
import com.eclipsesource.v8.V8Function;
import com.eclipsesource.v8.V8Object;

public class Main {

	public static void main(String[] args) {
		V8 engine = V8.createV8Runtime();

		Test t = new Test();
		engine.executeScript("var a = new Object();");
		V8Object obj = (V8Object) engine.get("a");
		obj.registerJavaMethod(t, "setFunc", "setFunc", new Class<?>[]{ V8Function.class });
		engine.executeScript("function b() { return 11; }");
		engine.executeScript("a.setFunc(b);");

		System.out.println(t.func.call(null, null));
	}
}
```

output:
```java
Exception in thread "main" java.lang.IllegalStateException: Object released
	at com.eclipsesource.v8.V8Value.checkReleased(V8Value.java:285)
	at com.eclipsesource.v8.V8Function.call(V8Function.java:76)
	at Main.main(Main.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by irbull** [comment]
Yes, those parameters are released. The reason for this is that there would be no other way to release them and they would cause a memory leak. If you want to keep a handle, call `func.twin()`. This and store the result of that. That Java object will point to the same underlying V8 Object, but this handle won't be released (until you release it).

**Comment by TomerAmirV** [comment]
Thanks!

**Comment by carl1990** [comment]
+1

mark
