### ISSUE TITLE
J2V8 4.6 On Linux

### ISSUE THREAD

**Issue by rajd86** [eclipsesource/J2V8#250]
Using J2V8 in an existing project and adding it using the following Maven dependency -

<dependency>
	    <groupId>com.eclipsesource.j2v8</groupId>
	    <artifactId>j2v8_linux_x86_64</artifactId>
	    <version>4.6.0</version>
</dependency>

But, NodeJS.createNodeJS(); fails with the following error message - "J2V8 native library not loaded"

But the same code works when I deploy the project on Windows with the following Maven dependency -

<dependency>
	    <groupId>com.eclipsesource.j2v8</groupId>
            <artifactId>j2v8_win32_x86_64</artifactId>
	    <version>4.6.0</version>
</dependency>

Looks like the .so file is not found on Linux.

Why this discrepancy with the same code on two platforms?

And what is the work around for this?

**Comment by rajd86** [comment]
We have tried adding the current directory (.) to the LD_LIBRARY_PATH system variable and it still is not able to locate the .so file

Below are the paths listed on the java.library.path property -

/export/CA/SharedComponents/lib
/opt/CA/CAlib
/export/CA/SharedComponents/Csam/SockAdapter/lib
/usr/java/packages/lib/amd64
/usr/lib64
/lib64
/lib
/usr/lib

**Comment by rajd86** [comment]
And here're two console outputs which tell us that the library is loaded first and then I get the error message -

2017-04-28 13:53:50.849
Java HotSpot(TM) 64-Bit Server VM warning: You have loaded library /home/jboss/libj2v8_linux_x86_64.so which might have disabled stack guard. The VM will try to fix the stack guard now. It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.

2017-04-28 13:53:51.061
ERROR INSTANTIATING MML2SCGCONVERTER :: J2V8 native library not loaded

**Comment by rajd86** [comment]
@irbull Hi Ian, need your help here.

I see that on Windows, the DLL file is copied to the USER HOME directory and the program successfully loads the library. Also, I do not see the "stack guard" warning message as well.

However, on Linux, although the SO file is copied into the USER HOME directory and the file permission is set to 755, still the library fails to load and also I get the "stack guard" warning.

Is there a possible Access Control issue here?

**Comment by irbull** [comment]
I finally (as of yesterday) have a working build for Linux that can be run on any platform. The build uses docker to setup a Linux environment, build J2V8 and then run the tests. The build also fixes the stack guard issue. If you clone J2V8 (and have docker installed) you should be able to:
```
cd j2v8
curl -O http://download.eclipsesource.com/j2v8/v8/node.out-7_4_0.tar.gz
./buildAll.sh
```
The `curl` command downloads the prebuilt node.js binaries. If you want, you can build those too. They build scripts for those are in https://github.com/eclipsesource/static-node-build.

The build script doesn't copy the final .so file out of the container, but that should be pretty easy.

**Comment by rajd86** [comment]
@irbull thanks for the response!

We are running our application on RHEL 6.7 (Santiago) x86_64

Can you please confirm if J2V8 can be run this platform? Also, is there a date when this fix will be available through a build?

**Comment by irbull** [comment]
I *cannot* confirm if it runs on this platform, as I've never tried it. I don't have a date to publish a new version of J2V8 yet. But I will be publishing a snapshot release within the next week for testing.

**Comment by rajd86** [comment]
Ok, thanks!

Looking forward to the snapshot release as we'll be able to test it at our end. :)

**Comment by rajd86** [comment]
@irbull
 
Hi Ian, are there any plans that J2V8 will be supported on RHEL?

Also, if your latest build fixes the warning message, when can we get that as a released version through maven artifact?

We have been trying to make use of J2V8 in our application and been stuck with this issue for weeks now. So, your help is much appreciated.

**Comment by irbull** [comment]
@rajd86 I have uploaded a 4.7.0-SNAPSHOT to maven central for Linux x86_64 [1]. Can you try this out and let me know if it works?

[1]https://oss.sonatype.org/content/repositories/snapshots/com/eclipsesource/j2v8/j2v8_linux_x86_64/4.7.0-SNAPSHOT/

**Comment by rajd86** [comment]
@irbull 

I tried the 4.7.0-SNAPSHOT on RHEL 6.7. I think we could boil down to the root cause here -

Could not load J2V8 library. Reasons:
        no libj2v8_linux_x86_64.so in java.library.path
        no j2v8_linux_x86_64 in java.library.path
        /home/qgao/libj2v8_linux_x86_64.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /home/qgao/libj2v8_linux_x86_64.so)

It's a library version issue as libstdc++.so.6.0.13 does not contain GLIBCXX_3.4.14.

Is there a recommended way to update the library so j2V8 could be run?

Thanks!

**Comment by cdupuis** [comment]
I'm also seeing this error with 4.7.1:

```Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons: 
	no libj2v8_linux_x86_64.so in java.library.path
	no j2v8_linux_x86_64 in java.library.path
	/home/travis/libj2v8_linux_x86_64.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/travis/libj2v8_linux_x86_64.so)
	at com.eclipsesource.v8.LibraryLoader.loadLibrary(LibraryLoader.java:79)
	at com.eclipsesource.v8.V8.load(V8.java:74)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:148)
	... 35 more```

with the following in the pom:

```
			<dependencies>
				<dependency>
					<groupId>com.eclipsesource.j2v8</groupId>
					<artifactId>j2v8_linux_x86_64</artifactId>
					<version>4.7.1</version>
				</dependency>
			</dependencies>
```

**Comment by rorye** [comment]
Experiencing the same issue:

```
Exception: java.lang.IllegalStateException: J2V8 native library not loaded
Exception: J2V8 native library not loaded
Exception: Could not load J2V8 library. Reasons:
	no libj2v8_linux_x86_64.so in java.library.path
	no j2v8_linux_x86_64 in java.library.path
	/home/202908/libj2v8_linux_x86_64.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /home/202908/libj2v8_linux_x86_64.so)
```

With J2V8 version: 

```
<dependency>
    <groupId>com.eclipsesource.j2v8</groupId>
    <artifactId>j2v8_linux_x86_64</artifactId>
    <version>4.8.0</version>
</dependency>
```

and OS version:

```
Red Hat Enterprise Linux Server release 6.9 (Santiago)
```

Any idea when this may be fixed ?

**Comment by matiwinnetou** [comment]
I don't think this problem can be fixed, in such case you have to use build system in the project and create yourself builds. I encourage you to do this anyway because 4.8.0 has nasty bugs that are already fixed in master but not released yet.

**Comment by matiwinnetou** [comment]
```

**Comment by Kangqiang0** [comment]
I meet the same problem when I run my 'jar' package on my **Ubuntu sever** after finishing the program on my **Windows 10** computer.  Here is the error and exception info:
_Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.IllegalStateException: J2V8 native library not loaded
	at com.eclipsesource.v8.V8.checkNativeLibraryLoaded(V8.java:195)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:149)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:110)
	at kangqiang.learn.Testj2v8.<clinit>(Testj2v8.java:10)
Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons: 
	no j2v8_linux_x86_64 in java.library.path
	/home/kangqiang/libj2v8_linux_x86_64.so: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /home/kangqiang/libj2v8_linux_x86_64.so)
	at com.eclipsesource.v8.LibraryLoader.loadLibrary(LibraryLoader.java:75)
	at com.eclipsesource.v8.V8.load(V8.java:71)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:145)_

The main problem is **"How to fix: [program name] /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version CXXABI_1.3.8' not found (required by [program name])"** . Here is the [solution.](https://stackoverflow.com/a/37628537/6876507) 

I made a stupid mistake ---- I packaged both the j2v8_linux_x86_64 and j2v8_win32_x86_64  while building the jar package using Maven plugin. After packaging the project, the we can run the jar PERFECTLY！

**Comment by igolus** [comment]
Hello,

I did face all the issues listed above while trying to run my [smocker ](https://github.com/igolus/smocker) application using docker,.The application is using wildfly and the challenge was to be able to run J2V8 inside wildfly using docker.

default [wildfly ](https://hub.docker.com/r/jboss/wildfly) image is based on centos:7 where it is not possible to install  gcc 4.9.

After a bit of search, i found a [wildfly image](https://github.com/mdopp/docker-wildfly) based on  unbuntu and an [image ](https://gist.github.com/alext234/5d84fbaecafd1d9d2249e5e2d9610910) containing unbutu with gcc 4.9  

Then i did recreate a docker file based on the two above see https://github.com/igolus/smocker/tree/master/docker and I am now able to run J2V8 within docker.

Hope it can help.
