### ISSUE TITLE
Could not load library u_strToLower_58

### ISSUE THREAD

**Issue by pinguxx** [eclipsesource/J2V8#288]
Any idea how to fix this:?

Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons: 
	no libj2v8_linux_x86_64.so in java.library.path
	/data/jenkins/jobs/j2v8/workspace/J2V8-master/jni/libj2v8_linux_x86_64.so: /data/jenkins/jobs/j2v8/workspace/J2V8-master/jni/libj2v8_linux_x86_64.so: undefined symbol: u_strToLower_58

seems to be building fine on my system, then when i do the maven verify i got this, or if i put the so file in the library path i got the same error

thanks for your help

**Comment by matiwinnetou** [comment]
Try to see if you have exactly the same version for linux of J2V8 as for other platforms, e.g. local dev.

**Comment by pinguxx** [comment]
i'm building this on jenkins, i may have a so or a jar in the classpath on the jvms, i will remove them and try again

**Comment by matiwinnetou** [comment]
It doesn't matter where you are building, do you have macos or windows version also present on the classpath?

**Comment by pinguxx** [comment]
i did not, i build a war with jenkins and it grabbed the j2v8_linux_x86_64-4.8.0.jar, try to run it but it couldn't load the library so i pasted the so into the classpath but that gave me another error
```
 C  [libj2v8_linux_x86_64.so+0xfa3809]  v8::base::OS::Abort()+0x9
```
So im trying to build node and the library... seems to be building correctly but the maven verify its failling because of the error u_strToLower_58

**Comment by matiwinnetou** [comment]
Interesting I didn't have such problems with latest release.

**Comment by pinguxx** [comment]
well after a clean up and build node and the library again, i still got in the maven verify
```
Exception in thread "Thread-19" java.lang.IllegalStateException: J2V8 native library not loaded
	at com.eclipsesource.v8.V8.checkNativeLibraryLoaded(V8.java:253)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:153)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:114)
	at com.eclipsesource.v8.utils.V8Executor.run(V8Executor.java:115)
Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons: 
	no libj2v8_linux_x86_64.so in java.library.path
	/data/jenkins/jobs/j2v8/workspace/J2V8-master/jni/libj2v8_linux_x86_64.so: /data/jenkins/jobs/j2v8/workspace/J2V8-master/jni/libj2v8_linux_x86_64.so: undefined symbol: u_strToLower_58

	at com.eclipsesource.v8.LibraryLoader.loadLibrary(LibraryLoader.java:79)
	at com.eclipsesource.v8.V8.load(V8.java:75)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:149)
	... 2 more
```

**Comment by pinguxx** [comment]
is the execstack step required?
