### ISSUE TITLE
Support 64 bit Windows

### ISSUE THREAD

**Issue by ManivannanDSekaran** [eclipsesource/J2V8#31]
When I run in Windows 7. I am getting the following error. While debugging around this, found the following error.
**"Can't load IA 32-bit .dll on a AMD 64-bit platform"**

vm_info: Java HotSpot(TM) 64-Bit Server VM (24.75-b04) for windows-amd64 JRE (1.7.0_75-b13), built on Dec 18 2014 17:15:01 by "java_re" with unknown MS VC++:1600
```java
Exception in thread "main" java.lang.IllegalStateException: J2V8 native library not loaded.
	at com.eclipsesource.v8.V8.checkNativeLibraryLoaded(V8.java:86)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:74)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:63)
	at Main.start(Main.java:10)
	at Main.main(Main.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons: 
	no j2v8_win32_amd64 in java.library.path

	at com.eclipsesource.v8.LibraryLoader.loadLibrary(LibraryLoader.java:71)
	at com.eclipsesource.v8.V8.load(V8.java:49)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:72)
	... 8 more

Process finished with exit code 1
```
I am not sure this library is tested on all the platform.

Thanks,
Mani

**Comment by irbull** [comment]
I've currently only built the native parts of J2V8 for 32 bit Windows [1]. It will take a while to build 64 bit windows as I need to build V8 for that platform first. 

[1] http://eclipsesource.com/blogs/2015/02/25/announcing-j2v8-2-0/

**Comment by angelozerr** [comment]
:+1: I would like to use this implementation too to implement tern server with J2V8.

**Comment by irbull** [comment]
J2V8 2.2 now supports 64 Bit Windows. The pom entry is:
```
<dependency>
  <groupId>com.eclipsesource.j2v8</groupId>
  <artifactId>j2v8_win32_x86_64</artifactId>
  <version>2.2.0</version>
</dependency>
```

Please try this and let me know if there are any problems.

**Comment by angelozerr** [comment]
Tahnks @irbull !

I will try it to start to implement tern server once you will hav etime to give me an answer for JSON support https://github.com/eclipsesource/J2V8/issues/32
