### ISSUE TITLE
Are native modules supported?

### ISSUE THREAD

**Issue by eli-jordan** [eclipsesource/J2V8#364]
Hi

I am trying to use a j2v8 to run some code that depends on a native node module i.e. a node module that is implemented in C/C++.

However, I have been unable to get this to work. Its not clear whether this use case is supported / is supposed to work at all?

The module that is failing for me is
https://github.com/Blizzard/node-rdkafka

The value of `process.versions` for j2v8 is
```
// j2v8
{ http_parser: '2.7.0',
  node: '7.4.0',
  v8: '5.4.500.45',
  uv: '1.10.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2j' }
```

When running the same code with node directly (which works just fine)
```
Versions: { http_parser: '2.7.0',
  node: '7.4.0',
  v8: '5.4.500.45',
  uv: '1.10.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2j',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }

```

The error I see is below. Which seems to indicate that it was unable to load the native module.
```

/Users/elijordan/dev/dx.next/code/prod-infra-cloudant-replication/clients/node/recovering-producer-node/node_modules/bindings/bindings.js:88: Error: Module did not self-register.
/Users/elijordan/dev/dx.next/code/prod-infra-cloudant-replication/clients/node/recovering-producer-node/node_modules/bindings/bindings.js:88: Error: Module did not self-register.
        throw e
        ^
Error: Module did not self-register.
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/elijordan/dev/dx.next/code/prod-infra-cloudant-replication/clients/node/recovering-producer-node/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/Users/elijordan/dev/dx.next/code/prod-infra-cloudant-replication/clients/node/recovering-producer-node/node_modules/node-rdkafka/librdkafka.js:10:32)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/elijordan/dev/dx.next/code/prod-infra-cloudant-replication/clients/node/recovering-producer-node/node_modules/node-rdkafka/lib/client.js:14:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/elijordan/dev/dx.next/code/prod-infra-cloudant-replication/clients/node/recovering-producer-node/node_modules/node-rdkafka/lib/kafka-consumer.js:13:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/elijordan/dev/dx.next/code/prod-infra-cloudant-replication/clients/node/recovering-producer-node/node_modules/node-rdkafka/lib/index.js:10:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/elijordan/dev/dx.next/code/prod-infra-cloudant-replication/clients/node/recovering-producer-node/lib/main/producer.js:3:15)
com.eclipsesource.v8.V8ScriptExecutionException
	at com.eclipsesource.v8.V8._executeFunction(Native Method)
	at com.eclipsesource.v8.V8.executeFunction(V8.java:1133)
	at com.eclipsesource.v8.V8Function.call(V8Function.java:94)
	at com.eclipsesource.v8.NodeJS.require(NodeJS.java:169)
	at com.ibm.dx.cloudant.replication.TryJ2V8$$anonfun$2$$anonfun$apply$mcV$sp$1.apply$mcV$sp(TryJ2V8.scala:81)
	at com.ibm.dx.cloudant.replication.TryJ2V8$$anonfun$2$$anonfun$apply$mcV$sp$1.apply(TryJ2V8.scala:78)
	at com.ibm.dx.cloudant.replication.TryJ2V8$$anonfun$2$$anonfun$apply$mcV$sp$1.apply(TryJ2V8.scala:78)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
	at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
	at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
	at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
	at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
	at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
	at org.scalatest.WordSpec.runTest(WordSpec.scala:1881)
	at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
	at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
	at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
	at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
	at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
	at com.ibm.dx.cloudant.replication.TryJ2V8.org$scalatest$BeforeAndAfterAll$$super$run(TryJ2V8.scala:49)
	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
	at com.ibm.dx.cloudant.replication.TryJ2V8.run(TryJ2V8.scala:49)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1340)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1334)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1334)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1010)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1500)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
```

**Comment by matiwinnetou** [comment]
I doubt this...

**Comment by eli-jordan** [comment]
@matiwinnetou Are you saying that native modules are not supported?
I thought that might be the case, since the loading of dynamically linked libraries would be different when running via JNI on the JVM. However, didn't see any mention of it in the docs.

**Comment by matiwinnetou** [comment]
This is what I meant. How would that work? J2V8 is running in embedded mode within JVM. Even if this could possiblz work you would have to compile in those native modules based on sources that you have within J2V8 (statically link). I don't think this is supported. @irbull may know more

**Comment by Mizumi** [comment]
@matiwinnetou [These APIs](https://github.com/nodejs/nan) might be relevant, at least in regards to cross-version compatibility.

**Comment by irbull** [comment]
No, unfortunately, these native modules are not supported, and I'm not sure how to even make that work.
