### ISSUE TITLE
Reoccurring "StartNodeJS Not Supported." error

### ISSUE THREAD

**Issue by kocko94** [eclipsesource/J2V8#369]
Still the issue seems to be reoccurring. The trigger of it is the following line:

```java
NodeJS nodeJS = NodeJS.createNodeJS();
```

The full trace of the exception is:

```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{example.com.testnodejs2/example.com.testnodejs2.MainActivity}: java.lang.UnsupportedOperationException: StartNodeJS Not Supported.
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2213)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2263)
 at android.app.ActivityThread.access$800(ActivityThread.java:135)
 at app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:136)
 at android.app.ActivityThread.main(ActivityThread.java:5038)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:515)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
 at dalvik.system.NativeStart.main(Native Method)
 Caused by: java.lang.UnsupportedOperationException: StartNodeJS Not Supported.
 at com.eclipsesource.v8.V8._startNodeJS(Native Method)
 at com.eclipsesource.v8.V8.createNodeRuntime(V8.java:857) 
 at com.eclipsesource.v8.NodeJS.createNodeJS(NodeJS.java:73)
 at com.eclipsesource.v8.NodeJS.createNodeJS(NodeJS.java:43)
 at de.tech.kv.testnodejs2.MainActivity.testNode(MainActivity.java:22)
 at de.tech.kv.testnodejs2.MainActivity.onCreate(MainActivity.java:17)
 at  android.app.Activity.performCreate(Activity.java:5445)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175
```

I've so far tried with the following J2V8 versions (either through gradle or I've manually downloaded the AAR file(s)):

```gradle
compile 'com.eclipsesource.j2v8:j2v8:4.1.0@aar'
compile 'com.eclipsesource.j2v8:j2v8:4.3.0@aar'
compile 'com.eclipsesource.j2v8:j2v8:4.8.0@aar'
//and some of the previous 3.x version but they do not support NodeJS
```
The funny part is that the built Loader is successfully loading the V8 native libs and I am able to run:
```java
V8 v8 = V8.createV8Runtime();
```
I've tested the code on
* OnePlus X (custom ROM with Android 7.1.1) with CPU architecture:
   *  OS.ARCH: armv7l
   *  CPU_ABI: armeabi-v7a
   *  CPU_ABI2: armeabi
* Pipo P9 Tablet (custom ROM with Android 4.4.2) with CPU architecture:
   *  OS.ARCH: armv7l
   *  CPU_ABI: armeabi-v7a
   *  CPU_ABI2: armeabi
* Samsung S7 (stock ROM with Android 7.1.2) with CPU architecture:
   *  OS.ARCH: armv8l
   *  CPU_ABI: armeabi-v8a
   *  CPU_ABI2: armeabi

I even tried to copy the downloaded .so libs to the 'libJni' folder but also with no success. Also I am using absolute empty project with nothing in it appart from the single java line from above so there are no other .so libraries or anything. Do you know the reason of this issue?

**Comment by DenBond7** [comment]
Please see #216

**Comment by irbull** [comment]
Yes, Node on Android was never a supported platform. I'd be happy if someone could make it work in a downstream project, but that is out of scope of J2V8.
