### ISSUE TITLE
JNI library output and failsafe/maven complains: Corrupted STDOUT by directly writing to native stream in forked JVM 1

### ISSUE THREAD

**Issue by bitsandbytes** [eclipsesource/J2V8#377]
I have a Junit test that tries to start up a nodejs webapp in a separate thread. Below is the method that starts it and registers a callback.

```
    private void initEngine(String scriptFolder) {
        ExecutorService executor = Executors.newSingleThreadExecutor();
        executor.submit(() -> {
            node = NodeJS.createNodeJS(new File(scriptFolder + "/" + "index.js"));
            this.scriptFolder = scriptFolder;

            JavaCallback callback = new JavaCallback() {
                @Override
                public Object invoke(V8Object receiver, V8Array parameters) {
                    logger.debug(parameters.get("0").toString());
                    return Boolean.TRUE;
                }
            };
            node.getRuntime().registerJavaMethod(callback, "javaLogging");
            while (node.isRunning()) {
              node.handleMessage();
            }
        });
    }
```
My Java test code calls an endpoint in the nodejs app, resulting in the following complaint.

```
[WARNING] Corrupted STDOUT by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /home/tmckernan/IdeaProjects/test/md-test-libs/target/failsafe-reports/2018-01-11T16-52-19_809-jvmRun1.dumpstream
java.util.concurrent.ExecutionException: javax.script.ScriptException: com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        ...
```

The failsafe report, in its entirety:
```
# Created on 2018-01-11T16:52:54.165
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream '[11/Jan/2018:16:52:54 +0000] HTTP/1.1 POST "/api/replication" 401 - 10.131 ms'.
java.lang.IllegalArgumentException: Stream stdin corrupted. Expected comma after third character in command '[11/Jan/2018:16:52:54 +0000] HTTP/1.1 POST "/api/replication" 401 - 10.131 ms'.
        at org.apache.maven.plugin.surefire.booterclient.output.ForkClient$OperationalData.<init>(ForkClient.java:506)
        at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.processLine(ForkClient.java:212)
        at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine(ForkClient.java:179)
        at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:88)
        at java.lang.Thread.run(Thread.java:745)
```

And the surefire developers have a bit in their FAQ about this error: http://maven.apache.org/surefire/maven-surefire-plugin/faq.html#corruptedstream

To me this looks like output from nodejs is what's "corrupting" the STDOUT. Does J2V8's native library have the capability to send all output to a file rather than use STDOUT?

**Comment by bitsandbytes** [comment]
I was able to use the solution in #246 to solve this. Thanks!
