### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by adonnini** [eclipsesource/J2V8#391]
Hi,
I looked for other places where I could ask this question. I did not find any.

I searched for other instances where my problem may have been reported but could not find any.

I am trying to build for android and getting the error below. What am I doing wrong?

Thanks,

Alex Donnini

Makefile:73: recipe for target 'node' failed
make: *** [node] Error 2
Traceback (most recent call last):
  File "build.py", line 18, in <module>
    bex.execute_build(args)
  File "/home/adonnini1/Development/J2V8/J2V8/build_system/build_executor.py", line 306, in execute_build
    execute_build_step(target_compiler, target_step)
  File "/home/adonnini1/Development/J2V8/J2V8/build_system/build_executor.py", line 222, in execute_build_step
    build_system.build(build_step)
  File "/home/adonnini1/Development/J2V8/J2V8/build_system/build_structures.py", line 83, in build
    self.exec_build(config)
  File "/home/adonnini1/Development/J2V8/J2V8/build_system/shell_build.py", line 27, in exec_build
    self.exec_cmd(shell_str, config)
  File "/home/adonnini1/Development/J2V8/J2V8/build_system/build_structures.py", line 96, in exec_cmd
    self.__exec_cmd_core(cmd, config, config.build_cwd)
  File "/home/adonnini1/Development/J2V8/J2V8/build_system/build_structures.py", line 105, in __exec_cmd_core
    utils.execute(cmd, cwd)
  File "/home/adonnini1/Development/J2V8/J2V8/build_system/build_utils.py", line 157, in execute
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command 'cd /home/adonnini1/Development/J2V8/J2V8 && android-gcc-toolchain arm --api 17 --host gcc-lpthread -C             sh -c "                \
            cd ./node;              \
            ./configure             \
            --without-intl          \
            --without-inspector     \
            --dest-cpu=arm        \
            --dest-os=android     \
            --without-snapshot      \
            --enable-static &&      \
            CFLAGS=-fPIC CXXFLAGS=-fPIC make -j4"              ' returned non-zero exit status 2

**Comment by adonnini** [comment]
Thanks. I believe I do have a working installation of the android-gcc-toolchain What do you mean by "working installation"?

Thanks

**Comment by adonnini** [comment]
By the way, at this point I am far more concerned about the other two issues I raised. Ii was able to work around this one

**Comment by irbull** [comment]
Builds are working again. We only officially support Android builds on Linux using Docker. Other builds are known to work (for example, I use MacOS without a problem).
