### ISSUE TITLE
nodejs diff apply error

### ISSUE THREAD

**Issue by xnetsc** [eclipsesource/J2V8#397]
nodejs diff apply
[apply-diff]
Applying Node.js patch: node.patches\7.4.0.diff
error: patch failed: common.gypi:183
error: common.gypi: patch does not apply
error: patch failed: deps/cares/common.gypi:80
error: deps/cares/common.gypi: patch does not apply
error: patch failed: deps/uv/common.gypi:87
error: deps/uv/common.gypi: patch does not apply
error: patch failed: src/node.h:414
error: src/node.h: patch does not apply
Traceback (most recent call last):
  File "nodejs.py", line 332, in <module>
    cmd_handler.function(sys.argv[3:])
  File "nodejs.py", line 272, in apply_diff
    utils.execute("git apply " + os.path.join("..", patch_file), "node")
  File "d:\code\j2v8\J2V8\build_system\build_utils.py", line 157, in execute
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command 'git apply ..\node.patches\7.4.0.diff' returned non-zero exit status 1

**Comment by ManuCosmo** [comment]
Same error here

**Comment by prad2019** [comment]
Same issue. Has anyone figured out the resolution? Is this a directory structure issue?

**Comment by huhuang03** [comment]
On windows, I find my issue is that `node.patches\7.4.0.diff` use 'CRLF` as line end. and in `node` folder, files are use `LF` as line end.

To resolve this. I change the `node.patches\7.4.0.diff`'s `CRLF` to `LF`. And it works.

If you use `vscode`, you can change at right bottom, there's a button.
