### ISSUE TITLE
Getting V8ScriptCompilationException while calling TestCafe script

### ISSUE THREAD

**Issue by anandxp** [eclipsesource/J2V8#426]
Error StackTrace
```
Exception in thread "main" undefined:1: SyntaxError: Unexpected reserved word
import { Selector } from 'testcafe';
^^^^^^
com.eclipsesource.v8.V8ScriptCompilationException
	at com.eclipsesource.v8.V8._executeIntegerScript(Native Method)
	at com.eclipsesource.v8.V8.executeIntegerScript(V8.java:911)
	at com.eclipsesource.v8.V8.executeIntegerScript(V8.java:436)
	at com.eclipsesource.v8.V8.executeIntegerScript(V8.java:418)
	at com.js.javatojs.FirstProgram.main(FirstProgram.java:16)
```

Program : 

```
import com.eclipsesource.v8.V8;

public class FirstProgram {

	public static void main(String[] args) {
		 V8  runtime = V8.createV8Runtime();
		 int result = runtime.executeIntegerScript(""
				 + "import { Selector } from 'testcafe';\n"
				 + "fixture `Getting Started`\n"
		         + ".page `http://devexpress.github.io/testcafe/example`;\n");
		 
		 System.out.println(result);
		 runtime.release();
		 
	}
}

```

**Comment by anandxp** [comment]
Any update on this bug ?
