### ISSUE TITLE
master branch appear '/bin/sh: 1: cmake: not found'

### ISSUE THREAD

**Issue by qianshui423** [eclipsesource/J2V8#502]
SHELL building android@arm => j2v8cmake
/bin/sh: 1: cmake: not found
Traceback (most recent call last):
  File "./build.py", line 18, in <module>
    bex.execute_build(args)
  File "/j2v8/build_system/build_executor.py", line 322, in execute_build
    execute_build_step(target_compiler, target_step)
  File "/j2v8/build_system/build_executor.py", line 231, in execute_build_step
    build_system.build(build_step)
  File "/j2v8/build_system/build_structures.py", line 96, in build
    self.exec_build(config)
  File "/j2v8/build_system/shell_build.py", line 27, in exec_build
    self.exec_cmd(shell_str, config)
  File "/j2v8/build_system/build_structures.py", line 113, in exec_cmd
    self.__exec_cmd_core(cmd, config, config.build_cwd)
  File "/j2v8/build_system/build_structures.py", line 122, in __exec_cmd_core
    utils.execute(cmd, cwd)
  File "/j2v8/build_system/build_utils.py", line 157, in execute
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command 'cd /j2v8 && python /j2v8/build_system/polyfills/mkdir.py ./cmake.out/android.arm/ && cd ./cmake.out/android.arm/ && python /j2v8/build_system/polyfills/rm.py CMakeCache.txt CMakeFiles/ && cmake             -DJ2V8_MONOLITH_LIB_DIR=android.arm             -DCMAKE_BUILD_TYPE=Release              -DJ2V8_CROSS_COMPILE:BOOL=TRUE  -DJ2V8_TARGET_ARCH:STRING=armeabi-v7a  -DJ2V8_NODE_ENABLED:BOOL=FALSE               -DCMAKE_TOOLCHAIN_FILE:STRING=/j2v8/docker/android/android.arm.toolchain.cmake              ../../         ' returned non-zero exit status 127
Traceback (most recent call last):
  File "build.py", line 18, in <module>
    bex.execute_build(args)
  File "/Users/liuxuehao/Documents/dasouche/ThirdLibrary/J2V8/build_system/build_executor.py", line 279, in execute_build
    execute_build_step(cross_compiler, cross_cfg)
  File "/Users/liuxuehao/Documents/dasouche/ThirdLibrary/J2V8/build_system/build_executor.py", line 231, in execute_build_step
    build_system.build(build_step)
  File "/Users/liuxuehao/Documents/dasouche/ThirdLibrary/J2V8/build_system/build_structures.py", line 96, in build
    self.exec_build(config)
  File "/Users/liuxuehao/Documents/dasouche/ThirdLibrary/J2V8/build_system/docker_build.py", line 187, in exec_build
    self.exec_host_cmd(docker_run_str, config)
  File "/Users/liuxuehao/Documents/dasouche/ThirdLibrary/J2V8/build_system/build_structures.py", line 105, in exec_host_cmd
    self.__exec_cmd_core(cmd, config, config.host_cwd)
  File "/Users/liuxuehao/Documents/dasouche/ThirdLibrary/J2V8/build_system/build_structures.py", line 122, in __exec_cmd_core
    utils.execute(cmd, cwd)
  File "/Users/liuxuehao/Documents/dasouche/ThirdLibrary/J2V8/build_system/build_utils.py", line 157, in execute
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command 'docker run --privileged -e KEY_ID=$KEY_ID -e KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD -e MAVEN_REPO_USER=$MAVEN_REPO_USER -e MAVEN_REPO_PASS=$MAVEN_REPO_PASS -P -v /Users/liuxuehao/Documents/dasouche/ThirdLibrary/J2V8:/j2v8 --name j2v8.android.arm j2v8-android /bin/bash -c "cd /j2v8; python ./build.py --cross-agent docker -t android -a arm  -knl  j2v8cmake j2v8jni j2v8cpp j2v8optimize j2v8java"' returned non-zero exit status 1
Waiting for docker process to exit...
j2v8.android.arm

**Comment by qianshui423** [comment]
my shell: 

#!/bin/bash

curl -O https://download.eclipsesource.com/j2v8/v8/libv8_7.4.288_monolith.zip
mkdir -p v8.out
unzip libv8_7.4.288_monolith.zip -d v8.out
start j2v8 build
python build.py -t linux -a x64 --docker j2v8cmake j2v8jni j2v8cpp j2v8optimize j2v8java j2v8test
python build.py -t android -a x86 --docker --keep-native-libs j2v8cmake j2v8jni j2v8cpp j2v8optimize j2v8java
python build.py -t android -a arm --docker --keep-native-libs j2v8cmake j2v8jni j2v8cpp j2v8optimize j2v8java

**Comment by ahmadov** [comment]
Could you please provide the OS and version? I can build on Linux using the commands from https://github.com/eclipsesource/J2V8/issues/487#issuecomment-554473647.
Please verify the `python` command refers to `python 2.x`.
Also, what is the `start j2v8 build` in your shell?

**Comment by qianshui423** [comment]
> Could you please provide the OS and version? I can build on Linux using the commands from [#487 (comment)](https://github.com/eclipsesource/J2V8/issues/487#issuecomment-554473647).
> Please verify the `python` command refers to `python 2.x`.
> Also, what is the `start j2v8 build` in your shell?

I solve it retry. Thanks. I suggest that dockerfile should  handle docker shell's executing result, and we can know that shell command executing status.
