### ISSUE TITLE
Invalid V8 thread access: current thread is Thread[Timer-0,5,main] while the locker has thread Thread[main,5,main]

### ISSUE THREAD

**Issue by schacker** [eclipsesource/J2V8#509]
I got an error when running the code below
```
class TestV8 {
    public static void main() {

        V8 runtime = V8.createV8Runtime("global");
        Console console = new Console();
        V8Object v8Console = new V8Object(runtime);
        runtime.add("console", v8Console);
        v8Console.registerJavaMethod(console, "log", "log", new Class[] { String.class });
        v8Console.registerJavaMethod(console, "err", "err", new Class[] { String.class });

        JavaVoidCallback callback = (receiver, parameters) -> {
            Timer timer = new Timer();
            System.out.println("first param："+parameters.getObject(0).toString());
            System.out.println("second param："+parameters.getInteger(1));
            timer.schedule(new TimerTask() {
                @Override
                public void run() {
                    V8Function v8Function = (V8Function)parameters.getObject(0);
                    v8Function.call(v8Function, null);
                    v8Function.close();
                }
            }, parameters.getInteger(1));

        };

        runtime.registerJavaMethod(callback, "setTimeout");
        runtime.executeScript("setTimeout(function() {console.log(123123)}, 10000);");
    }
}
```
Maybe i did something wrong...??  how to fix it ?
thanks for your help

**Comment by schacker** [comment]
Invalid V8 thread access: current thread is Thread[Timer-0,5,main] while the locker has thread Thread[main,5,main]

**Comment by schacker** [comment]
all exception
```
E/AndroidRuntime: FATAL EXCEPTION: Timer-0
    Process: com.example.myapplication, PID: 7057
    java.lang.Error: Invalid V8 thread access: current thread is Thread[Timer-0,5,main] while the locker has thread Thread[main,5,main]
        at com.eclipsesource.v8.V8Locker.checkThread(V8Locker.java:99)
        at com.eclipsesource.v8.V8.checkThread(V8.java:785)
        at com.eclipsesource.v8.V8Array.getObject(V8Array.java:450)
        at com.example.myapplication.TestV8$1.run(MainActivity.java:199)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
I/Process: Sending signal. PID: 7057 SIG: 9
```

**Comment by huhuang03** [comment]
I think the reason is V8.createRuntime() is in one thread, and v8.execute() is in other thread. They must in the same thread.

**Comment by schacker** [comment]
@huhuang03   The execution function of v8 cannot be executed in another thread? Can't I switch threads through the v8 instance API ? I see there is v8.acquire () and others

In any case, I have used another notification way to solve this problem that cannot be executed in other threads

**Comment by huhuang03** [comment]
Sorry for my poor english. Yes all v8 execute(include func call) must in same thread, because there's some thread check in j2v8 source.

You can try NodeJs. createNodeJS() to direct use `nodejs`.  There's a `setTimoutout` built-in.
See: https://eclipsesource.com/blogs/2016/07/20/running-node-js-on-the-jvm/

I have the same `setTimeout` issue. But In my situation, I can't use `nodejs` because I use use in android. And run the jar file by adb shell `app_process xxx`.

Even through I post the timeout function in same thread, there's another error: `the j2v8 object has already released`. I can't resolve it.

**Comment by schacker** [comment]
I have the same problem(`the j2v8 object has already released`), I also need to run on Android.

By the way, my english is not good, I am Chinese
哈哈哈哈哈哈

**Comment by huhuang03** [comment]
哈哈哈，我也是啊。If you resolve this, please notify me.

**Comment by huhuang03** [comment]
Hello. After some research. I find the rhino + rhino-android work fine in android. Maybe you can try.

**Comment by schacker** [comment]
@huhuang03   rhino's performance is not as good as j2v8, which is why we did not choose rhino.

**Comment by schacker** [comment]
@huhuang03  The following as a reference
https://www.chenhe.cc/p/162
https://neyoufan.github.io/2016/12/23/android/Android%20Js%E5%BC%95%E6%93%8E/%E5%9C%A8Android%E4%B8%8A%E4%BD%BF%E7%94%A8JS%E5%BC%95%E6%93%8E%E6%98%AF%E4%B8%80%E7%A7%8D%E4%BB%80%E4%B9%88%E6%A0%B7%E7%9A%84%E4%BD%93%E9%AA%8C%EF%BC%9F/

**Comment by huhuang03** [comment]
E.. In my situation, the performance is not the most important..
And I can't resolve the setTimeout (already released) issue. If your resolve this, please notify me.

**Comment by schacker** [comment]
Said in front, I am a front-end engineer
Then, in my scenario, it is necessary to consider the efficiency of js execution and the communication time
I inject the setTimeout function through registerJavaMethod, use Timer in the java callback, and then maintain a timer queue, through the queue

In the end, this issue was not resolved

**Comment by lucabiasotto** [comment]
> Said in front, I am a front-end engineer
> Then, in my scenario, it is necessary to consider the efficiency of js execution and the communication time
> I inject the setTimeout function through registerJavaMethod, use Timer in the java callback, and then maintain a timer queue, through the queue
> 
> In the end, this issue was not resolved

Hi @schacker  i have exactly the same problem!! :D  did you find a solution? 
Thanks
