### ISSUE TITLE
How to execute iife function?

### ISSUE THREAD

**Issue by chqianpront** [eclipsesource/J2V8#517]
when excute iife function, it throw error. How can it support iife

```
(function(txt){
    ...
})('hhh')
```

```
W/System.err:     at <anonymous>:8:1
    com.eclipsesource.v8.V8ScriptExecutionException
W/System.err:     at com.eclipsesource.v8.V8._executeScript(Native Method)
W/System.err:     at com.eclipsesource.v8.V8.executeScript(V8.java:1079)
W/System.err:     at com.eclipsesource.v8.V8.executeScript(V8.java:682)
W/System.err:     at com.eclipsesource.v8.V8.executeScript(V8.java:665)
```

**Comment by chqianpront** [comment]
update v8. solve.
