### ISSUE TITLE
cant run nodejs

### ISSUE THREAD

**Issue by SkyAlexV** [eclipsesource/J2V8#524]
Hello.

I can not start node with version 6.2.0.

Upon attempt:
`NodeJS nodeJS = NodeJS.createNodeJS();`

I get:
```
Exception in thread "main" java.lang.UnsupportedOperationException: StartNodeJS Not Supported.
	at com.eclipsesource.v8.V8._startNodeJS(Native Method)
	at com.eclipsesource.v8.V8.createNodeRuntime(V8.java:1017)
	at com.eclipsesource.v8.NodeJS.createNodeJS(NodeJS.java:101)
	at com.eclipsesource.v8.NodeJS.createNodeJS(NodeJS.java:48)
	at com.codejig.builder.TestJ2v8.main(TestJ2v8.java:18)
```

Build:
using instruction from https://github.com/eclipsesource/J2V8/blob/master/BUILDING.md
```bash
git clone git@github.com:eclipsesource/J2V8.git
cd ./J2V8
# update nodejs version in ./build_system/build_settings.py to 8.2.1
python2 nodejs.py git clone
python2 build.py --target linux --arch x64 --node-enabled --docker all
```

Thanks in advance.

**Comment by ahmadov** [comment]
Hi,

Please take a look at #469 and #477. We removed support for NodeJs.

**Comment by aoqilinjian** [comment]
how  solve the problem of not sopport nodejs???
