### ISSUE TITLE
Unable to import J2V8 from maven

### ISSUE THREAD

**Issue by Smagia** [eclipsesource/J2V8#526]
Hi, i added this maven dependency in my project:
```
<dependency>
            <groupId>com.eclipsesource.j2v8</groupId>
            <artifactId>j2v8</artifactId>
            <version>6.2.0</version>
            <type>aar.asc</type>
        </dependency>
```
but it doesn't work.
I tried to extract JAR from aar file and once i run the code i get this:

```
Exception in thread "main" java.lang.IllegalStateException: J2V8 native library not loaded (j2v8-linux-x86_64/j2v8-ubuntu-linux-x86_64)
	at com.eclipsesource.v8.V8.checkNativeLibraryLoaded(V8.java:263)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:155)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:116)
	at jsEngineTester.V8Engine.addValue(V8Engine.java:24)
	at jsEngineTester.main.testEngine(main.java:82)
	at jsEngineTester.main.main(main.java:41)
Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons: 
	no libj2v8-ubuntu-linux-x86_64.so in java.library.path
	/home/smagia/Downloads/lib/libj2v8-ubuntu-linux-x86_64.so: /lib/x86_64-linux-gnu/libm.so: invalid ELF header
	no libj2v8-linux-x86_64.so in java.library.path
	no j2v8-linux-x86_64 in java.library.path

	at com.eclipsesource.v8.LibraryLoader.loadLibrary(LibraryLoader.java:113)
	at com.eclipsesource.v8.V8.load(V8.java:77)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:151)
	... 4 more
```

 how can i fix it and why linux version isn't updated to 6.4?
Thanks for help

**Comment by Smagia** [comment]
I solved using 6.4 and selecting the .so file from j2v8_linux_x86_64.Jar (V. 4.8.0). Now it's working, but the efficiency of the engine got worse and i know that isn't a good solution. I'm doing a research for the university and i wanted to try the last J2V8 version, that's why i tried to run my code with 6.4 instead of j2v8_linux_x86_64 version.
