### ISSUE TITLE
const { JSDOM } = jsdom;

### ISSUE THREAD

**Issue by Osiris-Team** [eclipsesource/J2V8#562]
```log
D:\Coding\JAVA\Headless-Browser\browser-apis.js:3: SyntaxError: Unexpected token {

const { JSDOM } = jsdom;
      ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
com.eclipsesource.v8.V8ScriptExecutionException
	at com.eclipsesource.v8.V8._executeFunction(Native Method)
	at com.eclipsesource.v8.V8.executeFunction(V8.java:1000)
	at com.eclipsesource.v8.V8Function.call(V8Function.java:80)
	at com.eclipsesource.v8.NodeJS.require(NodeJS.java:143)
	at BrowserTest.testNodeJSRequire(BrowserTest.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine....
```

**Comment by ahmadov** [comment]
Hello @Osiris-Team,

which version of J2V8 do you use? I highly doubt it, but it's possible that the version you're using does not support that feature.

**Comment by Osiris-Team** [comment]
Latest available on maven

**Comment by Osiris-Team** [comment]
Closing because of no response

**Comment by caoccao** [comment]
> @caoccao dammn that wouldve been great a few days ago... Just integrated Node.js by myself into Java haha https://github.com/Osiris-Team/Headless-Browser

I thought you tried because there are other open issues referencing Javet.

I just took a glance at your project. It looks nice. I think it could be built upon Javet. And I don't recommend GraalJS because it has so many inconsistencies with V8/Chrome/ES so that in the long term 80% of development team's time would be spent on fighting with those inconsistencies and waiting for Oracle's mercy.
