### ISSUE TITLE
fail to build with commit 00dddaa

### ISSUE THREAD

**Issue by sollian** [eclipsesource/J2V8#566]
with commit 6ce9ff5, I can execute `build -t android -a arm --docker` successfully.
But when update to commit 00dddaa, I got an error: 

```
################################################################################
/usr/bin/python -u tools/mb/mb.py gen -f infra/mb/mb_config.pyl -m developer_default -b arm.release out.gn/arm.release
  
  Writing """\
  is_debug = false
  target_cpu = "x86"
  v8_target_cpu = "arm"
  """ to /v8build/v8/out.gn/arm.release/args.gn.
  
  /v8build/v8/buildtools/linux64/gn gen out.gn/arm.release --check
    -> returned 1
  ERROR at //build/config/sysroot.gni:65:11: Script returned non-zero exit code.
            exec_script("//build/dir_exists.py",
            ^----------
  Current dir: /v8build/v8/out.gn/arm.release/
  Command: python3 /v8build/v8/build/dir_exists.py /v8build/v8/build/linux/debian_sid_i386-sysroot
  Returned 127.
  stderr:
  
  python3: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
  
  See //build/config/gcc/BUILD.gn:8:1: whence it was imported.
  import("//build/config/sysroot.gni")
  ^----------------------------------
  See //build/config/BUILDCONFIG.gn:356:11: which caused the file to be included.
          [ "//build/config/gcc:symbol_visibility_hidden" ]
            ^--------------------------------------------
  GN gen failed: 1
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'tools/mb/mb.py', 'gen', '-f', 'infra/mb/mb_config.pyl', '-m', 'developer_default', '-b', 'arm.release', 'out.gn/arm.release']' returned non-zero exit status 1
The command '/bin/sh -c ./tools/dev/v8gen.py ${build_platform} -vv' returned a non-zero code: 1
Traceback (most recent call last):
  File "build.py", line 13, in <module>
    interactive.run_interactive_cli()
  File "/home/code/J2V8/build_system/build_interactive.py", line 58, in run_interactive_cli
    bex.execute_build(build_params)
  File "/home/code/J2V8/build_system/build_executor.py", line 275, in execute_build
    execute_build_step(cross_compiler, cross_cfg, True)
  File "/home/code/J2V8/build_system/build_executor.py", line 229, in execute_build_step
    build_system.build_v8(build_step)
  File "/home/code/J2V8/build_system/build_structures.py", line 76, in build_v8
    self.exec_v8_build(config)
  File "/home/code/J2V8/build_system/docker_build.py", line 99, in exec_v8_build
    self.exec_v8_cmd("docker build " + args_str + " -f Dockerfile -t \"" + image_name + "\" . ", config)
  File "/home/code/J2V8/build_system/build_structures.py", line 101, in exec_v8_cmd
    self.__exec_cmd_core(cmd, config, config.v8_cwd)
  File "/home/code/J2V8/build_system/build_structures.py", line 122, in __exec_cmd_core
    utils.execute(cmd, cwd)
  File "/home/code/J2V8/build_system/build_utils.py", line 157, in execute
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command 'docker build  --build-arg target_os=android --build-arg target_cpu=arm -f Dockerfile -t "v8-android-arm" . ' returned non-zero exit status 1
```

Any suggestions？

**Comment by emokhub** [comment]
For me, it fails for 6ce9ff5 commit also. any luck with the libcrypt.so.1 error?
or are you able to build j2v8 for any environment?
