### ISSUE TITLE
error when building windows-x64

### ISSUE THREAD

**Issue by AngelGamer29JA** [eclipsesource/J2V8#588]
Command: **build -t win32 -a x64 -ne**
`WARNING: skipping build step "v8" (not configured and/or supported for platform "win32")

Microsoft Windows [Versión 10.0.19045.2251]
Updating Maven configuration (./docker/shared/pom.xml)...
SHELL building win32@x64 => j2v8cmake
-- Selecting Windows SDK version  to target Windows 10.0.19045.
CMake Error at CMakeLists.txt:15 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 14.0.23107.0
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 23/11/2022 01:03:46 p. m..
    Project "C:\Users\popit\java\J2V8\cmake.out\win32.x64\CMakeFiles\3.25.0\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Users\popit\java\J2V8\cmake.out\win32.x64\CMakeFiles\3.25.0\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
    Done Building Project "C:\Users\popit\java\J2V8\cmake.out\win32.x64\CMakeFiles\3.25.0\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\Users\popit\java\J2V8\cmake.out\win32.x64\CMakeFiles\3.25.0\VCTargetsPath.vcxproj" (default target) (1) ->
      C:\Users\popit\java\J2V8\cmake.out\win32.x64\CMakeFiles\3.25.0\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:01.65

  Exit code: 1

-- Configuring incomplete, errors occurred!
See also "C:/Users/popit/java/J2V8/cmake.out/win32.x64/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "build.py", line 18, in <module>
    bex.execute_build(args)
  File "C:\Users\popit\java\J2V8\build_system\build_executor.py", line 322, in execute_build
    execute_build_step(target_compiler, target_step)
  File "C:\Users\popit\java\J2V8\build_system\build_executor.py", line 231, in execute_build_step
    build_system.build(build_step)
  File "C:\Users\popit\java\J2V8\build_system\build_structures.py", line 96, in build
    self.exec_build(config)
  File "C:\Users\popit\java\J2V8\build_system\shell_build.py", line 27, in exec_build
    self.exec_cmd(shell_str, config)
  File "C:\Users\popit\java\J2V8\build_system\build_structures.py", line 113, in exec_cmd
    self.__exec_cmd_core(cmd, config, config.build_cwd)
  File "C:\Users\popit\java\J2V8\build_system\build_structures.py", line 122, in __exec_cmd_core
    utils.execute(cmd, cwd)
  File "C:\Users\popit\java\J2V8\build_system\build_utils.py", line 157, in execute
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command 'cd C:/Users/popit/java/J2V8 && python C:/Users/popit/java/J2V8/build_system/polyfills/mkdir.py ./cmake.out/win32.x64/ && cd ./cmake.out/win32.x64/ && python C:/Users/popit/java/J2V8/build_system/polyfills/rm.py CMakeCache.txt CMakeFiles/ && cmake             ../../              -DJ2V8_TARGET_ARCH:STRING=x86_64  -DJ2V8_NODE_ENABLED:BOOL=TRUE                           -G"Visual Studio 14 2015 Win64"
        ' returned non-zero exit status 1`

**Comment by caoccao** [comment]
Please refer to #536 for detail.
