### ISSUE TITLE
Exception in thread "main" undefined:1: SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by aoqilinjian** [eclipsesource/J2V8#589]
not support js import????

Exception in thread "main" undefined:1: SyntaxError: Cannot use import statement outside a module
import MyMath from './mymathmodule.js';
^^^^^^
com.eclipsesource.v8.V8ScriptCompilationException
	at com.eclipsesource.v8.V8._executeScript(Native Method)
	at com.eclipsesource.v8.V8.executeScript(V8.java:1134)
	at com.eclipsesource.v8.V8.executeScript(V8.java:717)
	at com.eclipsesource.v8.V8.executeScript(V8.java:685)
	at com.topjoy.v8.function.TestFileScript4Import.main(TestFileScript4Import.java:27)

**Comment by aoqilinjian** [comment]
is anyone help me ?  how can i do ?
