### ISSUE TITLE
J2V8 native library not loaded

### ISSUE THREAD

**Issue by pianista215** [eclipsesource/J2V8#80]
I'm using the J2V8 as dependency in my project:

<dependency>
  <groupId>com.eclipsesource.j2v8</groupId>
  <artifactId>j2v8_win32_x86_64</artifactId>
  <version>3.0.0</version>
</dependency>

Just making an example:

V8 runtime = V8.createV8Runtime();
String result = runtime.executeStringScript(less);
System.out.println(result);
runtime.release();

Is showing me this error:

Exception in thread "main" java.lang.IllegalStateException: J2V8 native library not loaded.
	at com.eclipsesource.v8.V8.checkNativeLibraryLoaded(V8.java:149)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:135)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:96)
	...
Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons: 
	no j2v8_win32_x86 in java.library.path

	at com.eclipsesource.v8.LibraryLoader.loadLibrary(LibraryLoader.java:71)
	at com.eclipsesource.v8.V8.load(V8.java:69)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:131)
	... 3 more

Is there another requirement than using the maven dependency (like configure some vars, download the library, etc)?

Thank you

**Comment by pianista215** [comment]
I was using JVM of 32 bits, changing that the problem is solved :)

**Comment by irbull** [comment]
Thanks for summarizing the solution.

**Comment by carl1990** [comment]
+1 
I create V8 in new process and get this error
